# Generated by Django 2.2.10 on 2020-04-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0002_twofauser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofauser',
            name='is_active',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
