# Generated by Django 2.2.10 on 2020-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0003_twofauser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofauser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
