# Generated by Django 2.2.10 on 2020-04-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0005_auto_20200423_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofauser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
