# Generated by Django 2.2.10 on 2020-04-24 10:57

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0006_twofauser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='private_key',
            field=fernet_fields.fields.EncryptedTextField(null=True),
        ),
    ]
