# Generated by Django 2.2.10 on 2020-04-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0007_wallet_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofauser',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
