# Generated by Django 2.2.10 on 2020-04-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0008_twofauser_country_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactList',
        ),
    ]
