# Generated by Django 2.2.10 on 2020-04-26 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0010_contactlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='trx_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
