# Generated by Django 2.2.10 on 2020-04-27 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0012_auto_20200426_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='credit_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_wallet', to='twofa.Wallet'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='debit_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_wallet', to='twofa.Wallet'),
        ),
    ]
