# Generated by Django 2.2.10 on 2020-04-30 04:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0015_auto_20200427_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='banklist',
            name='bank_user_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
