# Generated by Django 2.2.10 on 2020-04-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0016_banklist_bank_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banklist',
            old_name='bank_user_id',
            new_name='bank_user',
        ),
    ]
