# Generated by Django 2.2.10 on 2020-04-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0017_auto_20200430_0448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankList',
        ),
    ]
