# Generated by Django 2.2.10 on 2020-04-30 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0019_banklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='twofa.Wallet'),
        ),
    ]
