# Generated by Django 2.2.10 on 2020-05-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0020_auto_20200430_1004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
