# Generated by Django 2.2.10 on 2020-05-09 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0023_auto_20200503_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
