# Generated by Django 2.2.10 on 2020-05-10 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0024_auto_20200509_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='sign_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
